name: 既存仕様の追加提案
title: "【改善】 "
description: "既存の仕様を変更したり、追加したい場合はこちら"
labels: 🔧要修正
#assignees: " "

body:
- type: markdown
  attributes:
    value: |
      ## 下記を記入してください
- type: input
  id: title
  attributes:
    label: 改善元の記載
    description: 変える元となる要素を記載してください。
    placeholder: issueのURLでも良いです
- type: textarea
  id: feature
  attributes:
    label: 内容
    description: 変更/追加したい内容を記載してください。
- type: input
  id: description
  attributes:
    label: 説明
    description: 変更/追加する理由を記載してください。
- type: dropdown
  id: priority
  attributes:
    label: 優先度
    description: この機能の実装優先度を選択してください。
    options:
      - 高(最優先で実装、実装しないと他が間に合わない)
      - 中(早めに実装、最優先ではないが実装しないと作成できない部分がある場合に)
      - 低(最後の方に実装しても順序上困らない場合)