name: タスク依頼
title: "【ToDo】 "
description: "やることを提示したい場合はこちら"
labels: ⌚️ToDO
#assignees: " "

body:
- type: markdown
  attributes:
    value: |
      ## 下記を記入してください
- type: textarea
  id: plan
  attributes:
    label: コード設計
    description: コードのフローや設計部分に補足が必要な場合は内容の前にあらかじめ記載してください。
    placeholder: <path>や<storage>から値を取得するなどの他との連携部分を記載してください。
- type: textarea
  id: feature
  attributes:
    label: タスク内容
    description: タスクの内容を記載してください。詳細な部分も含めて記入してください。
    placeholder: 数値等が決まっていない場合は決まっていないことも含めてください。誰がどう見ても同じ物を作れるように書くこと!!
- type: textarea
  id: problem
  attributes:
    label: 起こるであろう問題点
    description: 作成中に起こるであろう問題点があらかじめわかっている場合は記載してください。 
- type: dropdown
  id: priority
  attributes:
    label: 優先度
    description: この機能の実装優先度を選択してください。
    options:
      - 高(最優先で実装、実装しないと他が間に合わない)
      - 中(早めに実装、最優先ではないが実装しないと作成できない部分がある場合に)
      - 低(最後の方に実装しても順序上困らない場合)